PRODENG-2237 Added pruning policy resource
Mirantis/terraform-provider-msr pull request #24
Opened 2023-09-12 14:14 UTC by cranzy

# Description

*Added pruning policy resource

## Issue

https://mirantis.jira.com/browse/PRODENG-2237

2023-09-13 09:36 UTC, james-nesbitt requested changes
as you are doing a go module bump, you should also consider updating the versions of the critical imports, such as the terraform-plugin-framework.

Also, can you try to update the golangci and goreleaser GH action versions, for which there are updates as reported by dependabot.

2023-09-13 09:36 UTC, james-nesbitt commented on internal/client/utils.go
> +	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
with this line you have coupled the client to the terraform plugin framework, which is against the paradigm used for the client at this time.  The PruningPolicy methods are likely best left in the provider, with the client imported into the provider as needed.

2023-09-13 14:21 UTC, cranzy commented on internal/client/utils.go
> +	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
Decided not to have duplicate structs

2023-09-14 10:56 UTC, james-nesbitt approved these changes

2023-09-14 12:09 UTC, merged